### ISSUE TITLE
regenerate POT please

### ISSUE THREAD

**Issue by leonardcj** [sugarlabs/iknowMadagascar#1]
Please regenerate the POT file.  In the current one there is an error that is fixed in the code.
# : recursos/comun/datos/commons.py:9

msgid ""
"...tomorrow I have a\n"
"test about America..."
msgstr ""

**Comment by AlanJAS** [comment]
How? python setup.py genpot? and push the changes? or in Pootle?

**Comment by leonardcj** [comment]
In the repo please, I will upload to Pootle and refresh languages.

**Comment by AlanJAS** [comment]
Ready!

**Comment by leonardcj** [comment]
Thanks
